### ISSUE TITLE
请把预览页面的滚动条调整一下

### ISSUE THREAD

**Issue by Arduka** [imgcook/imgcook#108]
在布局模式的编辑页面，请把<div class="imgcook-canvas-magnifier">往上挪一点，他遮挡了底部滚动条，十分不方便

**Comment by yukrain** [comment]
能截个图看一下是指哪里吗？

**Comment by Arduka** [comment]
就是把div.imgcook-canvas-magnifier往上挪一点，他挡住了底部滚动条
![QOHKH$W6H1VPVMX4JF{ )B0](https://user-images.githubusercontent.com/50941239/135421522-78cf47b5-f2df-49a9-b9b9-b1ba4a71c415.png)

**Comment by chang20159** [comment]
> 就是把div.imgcook-canvas-magnifier往上挪一点，他挡住了底部滚动条 ![QOHKH$W6H1VPVMX4JF{ )B0](https://user-images.githubusercontent.com/50941239/135421522-78cf47b5-f2df-49a9-b9b9-b1ba4a71c415.png)

21年 12月份，编辑器发布新版本，已无滚动条。
