### ISSUE TITLE
今天代码生成页面更新后，应用设置失效了

### ISSUE THREAD

**Issue by ZhouG2** [imgcook/imgcook#114]
你好！
        我们一直使用官方提供的uni-app开发规范生成代码，设计稿宽度为390，之前在应用设置里将设计稿宽度改为390可以导出750rpx标准的scss文件。
       今天发现代码生成页面更新了，应用设置也不起作用了，无论如何只能导出390rpx的scss文件

**Comment by yukrain** [comment]
你好，这里我们下周会加上uniapp的宽度设置。您可以先修改一下左下角 dslConfig.responseWidth 的值。
![image](https://user-images.githubusercontent.com/5093226/146349287-726dca58-10d7-4afd-be1e-71f4b600ff9b.png)
