### ISSUE TITLE
这个项目是不是不维护了？

### ISSUE THREAD

**Issue by omnip620** [imgcook/imgcook#126]
项目是不是不维护了，看官网的 changelogs 只更新到 2022.2。

**Comment by yukrain** [comment]
> 项目是不是不维护了，看官网的 changelogs 只更新到 2022.2。

目前在维护核心功能，有问题欢迎反馈

**Comment by miaojing** [comment]
https://imgcook.alibaba-inc.com/docs/change-log
changelog 已经更新，我们目前主要基于内部需求迭代核心的生成代码准确度能力，对外的产品功能增加不多，用户可感知的外部功能变化不大。

**Comment by miaojing** [comment]
https://www.imgcook.com/docs/change-log

哦 上面是内部打开的地址，不好意思，外网地址如上
