### ISSUE TITLE
安装插件不成功

### ISSUE THREAD

**Issue by 1475142232** [imgcook/imgcook#69]
If you want to communicate with us further, please scan the qr code below:
![imgcook钉钉群二维码](https://ai-sample.oss-cn-hangzhou.aliyuncs.com/imgcook%E9%92%89%E9%92%89%E7%BE%A4%E4%BA%8C%E7%BB%B4%E7%A0%81.jpeg)

* **pluginVersion**:
* **sketchVersion**:
* **sketchFile**:

![image](https://user-images.githubusercontent.com/25600940/82987022-76798480-a029-11ea-8ab3-6c6ac8296f53.png)
![image](https://user-images.githubusercontent.com/25600940/82987112-990b9d80-a029-11ea-9831-120ac91cddf5.png)
![image](https://user-images.githubusercontent.com/25600940/82987154-ac1e6d80-a029-11ea-9ec6-2f8bad49e6ca.png)
![image](https://user-images.githubusercontent.com/25600940/82987233-cd7f5980-a029-11ea-9936-c8d290ace1c3.png)
![image](https://user-images.githubusercontent.com/25600940/82987301-e2f48380-a029-11ea-8b84-9522549bebed.png)

**Comment by gindis** [comment]
参考文档手动安装试下，https://www.imgcook.com/docs?slug=install-plugin#F0vyC
