### ISSUE TITLE
ps-模块 className 前缀无效

### ISSUE THREAD

**Issue by chinesehope** [imgcook/imgcook#74]
![image](https://user-images.githubusercontent.com/37769397/88156474-10316c80-cc3c-11ea-87c6-61dd9501ab75.png)
![image](https://user-images.githubusercontent.com/37769397/88156518-22aba600-cc3c-11ea-963c-357f0d51e865.png)
ps的组模块添加了#classPre:类名#无效

**Comment by wushiwein119** [comment]
目前ps还不支持sketch插件的协议，这个还在计划添加中
