### ISSUE TITLE
欢迎加入 imgcook 社区上帝群

### ISSUE THREAD

**Issue by gindis** [imgcook/imgcook#76]
扫描二维码加入 [钉钉](https://www.dingtalk.com/) 讨论组

![](https://gw.alicdn.com/tfs/TB1UW5UcIVl614jSZKPXXaGjpXa-750-990.jpg)

**Comment by zhaohaomian** [comment]
过期了~官网的二维码也过期了

**Comment by yukrain** [comment]
> 过期了~官网的二维码也过期了

已重新更新

**Comment by Gtanxingwen** [comment]
二维码过期了

**Comment by KikiTsin** [comment]
过期了

**Comment by 94cstyles** [comment]
过期了
