### ISSUE TITLE
导出失败：不能完成命令，因为没有足够内存

### ISSUE THREAD

**Issue by zhupengfu** [imgcook/imgcook#77]
error: 发生了常规 Photoshop 错误。该功能可能无法在这个版本的 Photoshop 中使用。 - 不能完成命令，因为没有足够内存(RAM)。

**Comment by rickycao-qy** [comment]
你好，请问是所有的设计稿导出都有这个问题还是某个特定的设计稿，设计稿大小大约是多大

**Comment by zhupengfu** [comment]
设计稿大小12.2Mb


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imgcook/imgcook"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月3日(星期一) 晚上8:21
收件人:&nbsp;"imgcook/imgcook"<imgcook@noreply.github.com&gt;;
抄送:&nbsp;"一个没有感情的学习机"<1912632741@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [imgcook/imgcook] 导出失败：不能完成命令，因为没有足够内存 (#77)





 
你好，请问是所有的设计稿导出都有这个问题还是某个特定的设计稿，设计稿大小大约是多大
