### ISSUE TITLE
导出失败 error: 请选中图层组或者文档节点进行导出

### ISSUE THREAD

**Issue by kaigeshuai** [imgcook/imgcook#79]
![企业微信截图_20200814015357](https://user-images.githubusercontent.com/37362837/90169372-16e17880-ddd1-11ea-8cdf-b1cdd1bcfe13.png)
If you want to communicate with us further, please scan the qr code below:
![imgcook钉钉群二维码](https://ai-sample.oss-cn-hangzhou.aliyuncs.com/imgcook%E9%92%89%E9%92%89%E7%BE%A4%E4%BA%8C%E7%BB%B4%E7%A0%81.jpeg)
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, such as the following:

**Expected behavior**

**Screenshots**

*If you use sketch(Please complete the following information):*
 - PluginVersion: imgcook plugin version [e.g. 1.7.1]
 - sketchVersion: sketch version [e.g. 55.1]
 - sketchFile: problematic sketch file,compressed into zip

**Additional context**

**Comment by gindis** [comment]
![image](https://user-images.githubusercontent.com/758046/90200695-41502780-de0b-11ea-9741-8bd751e283d5.png)

请按照提示 ”请选中图层组或者文档节点进行导出“ 操作（如图）
