### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by bulolo** [imgcook/imgcook#81]
![image](https://user-images.githubusercontent.com/10026498/93765912-3aa5a300-fc48-11ea-8347-ab89c877e466.png)
![image](https://user-images.githubusercontent.com/10026498/93765943-45603800-fc48-11ea-92bf-033b6ff1aa0d.png)

**Comment by gindis** [comment]
需要手动授权，参考这个教程试下 https://www.imgcook.com/docs?slug=install-plugin#810is
