### ISSUE TITLE
sketch 插件无法下载

### ISSUE THREAD

**Issue by good-father** [imgcook/imgcook#82]
官网 https://www.imgcook.com/ 首页的下载链接, 无法下载.

**Comment by gindis** [comment]
提示什么错误，这边试了下可以下载的。

**Comment by good-father** [comment]
![image](https://user-images.githubusercontent.com/18495604/97253058-6f5bda00-1846-11eb-8629-86c9819b75e2.png)

使用chrome、safari 浏览器试了，都不行

**Comment by rickycao-qy** [comment]
> ![image](https://user-images.githubusercontent.com/18495604/97253058-6f5bda00-1846-11eb-8629-86c9819b75e2.png)
> 
> 使用chrome、safari 浏览器试了，都不行

点击右边那个小三角然后点保留就好了

**Comment by gindis** [comment]
![image](https://user-images.githubusercontent.com/758046/97255156-f1e69880-184a-11eb-99e1-c061d6781b5d.png)
@good-father Chrome 10 月发的版本加了限制，先按 @rickycao-qy 说的步骤下载下，改好了要等封网结束再上线。

**Comment by good-father** [comment]
@gindis 谢谢, 已解决
