### ISSUE TITLE
创建团队失败，blocked:mixed-content

### ISSUE THREAD

**Issue by zhouzhili** [imgcook/imgcook#84]
没法创建团队和保存设计

**Comment by gindis** [comment]
有错误提示吗，在 sketch 里还是 web 上创建，可以截个图看下吗，

**Comment by zhouzhili** [comment]
今天发现创建团队可以了，但是创建模块不行，我是直接拖了一个form表单组件
![image](https://user-images.githubusercontent.com/14259932/99356083-7ffeed80-28e4-11eb-97cf-19314f9e7ee2.png)

**Comment by gindis** [comment]
![image](https://user-images.githubusercontent.com/758046/99356201-bd637b00-28e4-11eb-8bad-da3e4b2e5d47.png)
麻烦点击(如图)粘贴协议发看下，可能是协议被安全识别有风险被拦了。

**Comment by zhouzhili** [comment]
好的，谢谢
