### ISSUE TITLE
Download imgcook for figma：https://www.figma.com/community/plugin/951438743886938495/imgcook

### ISSUE THREAD

**Issue by chenzefeng09** [imgcook/imgcook#86]
公司的设计团队已经从sketch转向使用figma了，这看起来是一个业界的趋势，imgcook有考虑对接figma吗？

**Comment by gindis** [comment]
暂时没有，有兴趣一起共建 imgcook figma 插件吗

**Comment by chenzefeng09** [comment]
有兴趣，但是不一定有时间...怎么做figma插件有文档，怎么对接imgcook没看到有说明。imgcook sketch插件也不是开源的吧？
现在有一些figma转sketch的插件，勉强可用，但是会有一些偏差或者丢失信息的情况。

**Comment by gindis** [comment]
> 有兴趣，但是不一定有时间...怎么做figma插件有文档，怎么对接imgcook没看到有说明。imgcook sketch插件也不是开源的吧？
> 现在有一些figma转sketch的插件，勉强可用，但是会有一些偏差或者丢失信息的情况。

1. 把 figma 中设计协议导出&转换成 imgcook Schema 就可以（有需要支持的可以联系我），参考文档：https://www.imgcook.com/docs?slug=d2c-schema-demo
2. 嗯，imgcook sketch插件还没对外开源
3. 建了个 [imgcook figma 插件 Repo](https://github.com/imgcook/imgcook-figma) 已加你权限，若有时间可以一起共建哈

**Comment by chenzefeng09** [comment]
图片上传阿里图床的是走的哪个服务？

**Comment by gindis** [comment]
> 图片上传阿里图床的是走的哪个服务？

加钉钉 @笑翟 私聊哈，上传服务需要授权验证

**Comment by chenzefeng09** [comment]
粗略写了一版，已经push了 。搜不到笑翟，提示无法找到该用户...

**Comment by gindis** [comment]
> 粗略写了一版，已经push了，上传图床的服务还需要替换为阿里的 。搜不到笑翟，提示无法找到该用户...

好的，搜下 gindis 这个账号，或者发下你的钉钉号，我来加你。

**Comment by chenzefeng09** [comment]
> > 粗略写了一版，已经push了，上传图床的服务还需要替换为阿里的 。搜不到笑翟，提示无法找到该用户...
> 
> 好的，搜下 gindis 这个账号，或者发下你的钉钉号，我来加你。

已加

**Comment by gindis** [comment]
Download imgcook for figma：https://www.figma.com/community/plugin/951438743886938495/imgcook
