### ISSUE TITLE
文本绑定值不生效

### ISSUE THREAD

**Issue by chenzefeng09** [imgcook/imgcook#89]
在还原涉及稿时，目前对文档绑定值的设置不生效了。不管是常量还是绑定变量，预览稿都没有变化

![image](https://user-images.githubusercontent.com/7556537/110267011-ef1a6200-7ff9-11eb-9e08-626d07d75eeb.png)

**Comment by gindis** [comment]
模块地址发看下，试了下没问题

**Comment by chenzefeng09** [comment]
https://www.imgcook.com/editor#/?id=71548

**Comment by gindis** [comment]
重新刷新页面修改试下，由于插件导出节点属性 lines 为 null 导致的问题。

**Comment by chenzefeng09** [comment]
ok了，figma插件会导出lines为null的，我看看怎么改下
