### ISSUE TITLE
创建DSL失败

### ISSUE THREAD

**Issue by amasikas** [imgcook/imgcook#90]
**Describe the bug**
创建自定义DSL时，提交后等待很长时间，总是提示网络异常。

**Screenshots**
![image](https://user-images.githubusercontent.com/8335440/111590554-332f1300-8801-11eb-8a7d-cc373de52505.png)

![image](https://user-images.githubusercontent.com/8335440/111590915-adf82e00-8801-11eb-8819-1e1211195343.png)

**Comment by gindis** [comment]
多试几次看下（国内访问 github 不是很稳定导致的超时），如果还是不可以，把要创建的 DSL 信息发下，手动帮你创建下。
