### ISSUE TITLE
error: 发生了常规 Photoshop 错误。该功能可能无法在这个版本的 Photoshop 中使用。 - 命令"选择"当前不可用。

### ISSUE THREAD

**Issue by LoveEocding** [imgcook/imgcook#92]
error: 发生了常规 Photoshop 错误。该功能可能无法在这个版本的 Photoshop 中使用。 - 命令"选择"当前不可用。

**Comment by gindis** [comment]
方便截图看下吗？

**Comment by LoveEocding** [comment]
![image](https://user-images.githubusercontent.com/29218661/114488231-961a9b00-9c43-11eb-8f78-e58735accc74.png)

**Comment by LoveEocding** [comment]
> 方便截图看下吗？

![image](https://user-images.githubusercontent.com/29218661/114488250-a16dc680-9c43-11eb-8abb-a08fd5d92c89.png)

**Comment by gindis** [comment]
需要选中对应图层组导出，检查看下？

**Comment by gindis** [comment]
已解决

**Comment by LeasyBXDD** [comment]
怎么解决的？我现在2020版本的PS还是会出现这个问题，选中图层组了已经

**Comment by ynot16** [comment]
2022还有问题
