### ISSUE TITLE
我创建了自定义DSL  但是github一直没收到邀请者通知

### ISSUE THREAD

**Issue by LoveEocding** [imgcook/imgcook#94]
我创建了自定义DSL  但是github一直没收到邀请者通知

**Comment by gindis** [comment]
![image](https://user-images.githubusercontent.com/758046/114488321-be09fe80-9c43-11eb-96ef-8b08b79a5162.png)

查了有发邀请的，需要到设置的 github 邮箱里查收，或点 https://github.com/imgcook-dsl/test_tongzhi/invitations

**Comment by LoveEocding** [comment]
感谢 需要在邮箱中查看。我看文档是是github消息
