### ISSUE TITLE
Would you like to add a license?

### ISSUE THREAD

**Issue by gingerhot** [imgcook/imgcook#95]
I have tried this tool in imgcook.com, it's great. But I can't find a license in this repo, would you like to add one?  

It seems that this isn't an open source project? 

Thanks!

**Comment by gindis** [comment]
Sure. Open and free to use, there is no plan to fully open source for the time being. In the future, data and algorithms will be open sourced through http://github.com/alibaba/pipcook, welcome to follow.

**Comment by gingerhot** [comment]
Thanks for answering!
