### ISSUE TITLE
【Plugin】一直停留在‘模块数据导出中......’

### ISSUE THREAD

**Issue by Teemwu** [imgcook/imgcook#96]
**Describe the bug**
Photoshop 的 imgcook 插件，点击“导出数据“按钮一直停留在‘模块数据导出中......’。

**To Reproduce**
Steps to reproduce the behavior, such as the following:
1. 选择要导出的图层组
2. 打开 imgcook 插件，点击“导出数据”
3. Photoshop 界面会显示弹窗（插件在执行切图么？）
4. 然后过了一会插件就一直显示在“模块数据导出中.....”了

**Expected behavior**
1. 希望能正常导出可用文件
2. 如果解析出问题了能抛出具体错误

**Screenshots**
![image](https://user-images.githubusercontent.com/16522288/114967912-e2feab80-9ea7-11eb-924b-2218b50151b5.png)
![image](https://user-images.githubusercontent.com/16522288/114968517-1a218c80-9ea9-11eb-9710-69c7888e2ad1.png)

*If you use sketch(Please complete the following information):*
 - PluginVersion: 1.1.3
 - PhotoshopVersion: 22.0.0(mac) & 20.0.4(win)
 - PsdFile: 如截图，图层组内就两张图片

**Additional context**
相关提问 #https://github.com/imgcook/imgcook/issues/35#issue-528017445

**Comment by gindis** [comment]
什么时候安装的插件？重新手动安装试下（有些配置更新过需要重新安装下插件），插件安装文档：https://www.imgcook.com/docs/install-plugin

**Comment by Teemwu** [comment]
感谢回答，重装后确实可用了。
