### ISSUE TITLE
通过PSD导入，报error E01002，不知是什么问题 

### ISSUE THREAD

**Issue by aceaddi** [imgcook/imgcook#98]
如题。

导入提供的psd能正常使用，导入我们UI提供的psd文件，则都是报该错误，但是没有进一步提示具体是什么错误

**Comment by gindis** [comment]
可以截图看下吗

**Comment by aceaddi** [comment]
抱歉，公司网络不知为何上传不了截图。


就是选择psd文件导入UI稿的弹窗页面，选择导入我们UI提供的psd文件时，会在右上角弹出一个提示条，提示条的内容只有简单2句：

error
E01002


但是我通过Network面板查看的话，所调用到的接口都是调用成功的。

**Comment by aceaddi** [comment]
@gindis 

我想可能是psd没按照规范来设计导致的？？？

**Comment by gindis** [comment]
> @gindis
> 
> 我想可能是psd没按照规范来设计导致的？？？

可以发设计稿看下吗
